spring:
  config:
    import: optional:nacos:localhost:8848
  application:
    name: shop-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

server:
  port: ${SERVER_PORT:9341}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
