apiVersion: v1
kind: Secret
metadata:
  name: super-market-secret
  namespace: super-market
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root123"
  MYSQL_APP_PASSWORD: "app_user123"
  REDIS_PASSWORD: "redis123"
  MINIO_ROOT_PASSWORD: "minioadmin123"
  JWT_SECRET: "super-market-jwt-secret-min-256-bits-long-key-change-in-production"
