apiVersion: v1
kind: Service
metadata:
  name: category-service
  namespace: super-market
  labels:
    app: category-service
spec:
  selector:
    app: category-service
  ports:
    - name: dubbo
      port: 9312
      targetPort: 9312
      protocol: TCP
  type: ClusterIP
