apiVersion: v1
kind: Service
metadata:
  name: coupon-service
  namespace: super-market
  labels:
    app: coupon-service
spec:
  selector:
    app: coupon-service
  ports:
    - name: dubbo
      port: 9351
      targetPort: 9351
      protocol: TCP
  type: ClusterIP
