apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: super-market
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - name: dubbo
      port: 8999
      targetPort: 8999
      protocol: TCP
  type: ClusterIP
