apiVersion: v1
kind: Service
metadata:
  name: notify-service
  namespace: super-market
  labels:
    app: notify-service
spec:
  selector:
    app: notify-service
  ports:
    - name: dubbo
      port: 9372
      targetPort: 9372
      protocol: TCP
  type: ClusterIP
