apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: super-market
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - name: dubbo
      port: 9331
      targetPort: 9331
      protocol: TCP
  type: ClusterIP
