apiVersion: v1
kind: Service
metadata:
  name: platform-service
  namespace: super-market
  labels:
    app: platform-service
spec:
  selector:
    app: platform-service
  ports:
    - name: dubbo
      port: 9381
      targetPort: 9381
      protocol: TCP
  type: ClusterIP
