apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: super-market
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - name: dubbo
      port: 9311
      targetPort: 9311
      protocol: TCP
  type: ClusterIP
