apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: super-market
  labels:
    app: review-service
spec:
  selector:
    app: review-service
  ports:
    - name: dubbo
      port: 9314
      targetPort: 9314
      protocol: TCP
  type: ClusterIP
