apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: super-market
  labels:
    app: search-service
spec:
  selector:
    app: search-service
  ports:
    - name: dubbo
      port: 9361
      targetPort: 9361
      protocol: TCP
  type: ClusterIP
