spring:
  application:
    name: platform-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:nacos:localhost:8848"

server:
  port: ${SERVER_PORT:9381}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /api/platform/v3/api-docs
  group-configs:
    - group: service-platform
      paths-to-match: /api/platform/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
