spring:
  application:
    name: payment-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  config:
    import: "optional:nacos:${DOCKER_HOST_IP:localhost}:${NACOS_PORT:8848}"

server:
  port: ${SERVER_PORT:9331}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /api/payment/v3/api-docs
  group-configs:
    - group: service-payment
      paths-to-match: /api/payment/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always