spring:
  application:
    name: payment-service
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

server:
  port: ${SERVER_PORT:9031}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
